server:
  port: 8000

spring:
  application:
    name: bilibili-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            maxAge: 3600
      routes:
        #  legacy 单体应用路由
        - id: bilibili-legacy-service
          uri: lb://bilibili-legacy-service
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: debug
